spring.application.name=autohub
server.port=${PORT:8080}

# Database Connection
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Fixed URL (Removed the double jdbc:postgresql://)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://mainline.proxy.rlwy.net:39496/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:jQFEWwZnILZzlETslDCuWSQTJbpIYoQU}