spring.application.name=autohub
server.port=${PORT:8080}

# Database Connection
# Force data.sql to run every time
spring.sql.init.mode=always
# Ensure Hibernate doesn't interfere with the script
spring.jpa.defer-datasource-initialization=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
# Optional: See the SQL in your IntelliJ console to confirm it's running
spring.jpa.show-sql=true
# Fixed URL (Removed the double jdbc:postgresql://)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://mainline.proxy.rlwy.net:39496/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:jQFEWwZnILZzlETslDCuWSQTJbpIYoQU}